//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektCona1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month
    {
        public int Id { get; set; }
        public Nullable<int> month1 { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> mesečnePadavine { get; set; }
        public Nullable<int> IdPostaje { get; set; }
    }
}
