//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektCona1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podatki
    {
        public int Id { get; set; }
        public int IdPostaje { get; set; }
        public Nullable<System.DateTime> Cas { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<decimal> Vlaga { get; set; }
        public Nullable<decimal> Tlak { get; set; }
        public Nullable<decimal> Napetost { get; set; }
        public Nullable<decimal> Padavine { get; set; }
    
        public virtual Postaje Postaje { get; set; }
    }
}
