//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektCona1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postaje()
        {
            this.Podatki = new HashSet<Podatki>();
        }
    
        public int IdPostaje { get; set; }
        public string Naslov { get; set; }
        public string ImePostaje { get; set; }
        public string OpisPostaje { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public string DrzavaPostaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podatki> Podatki { get; set; }
    }
}
